#[path = "connect.rs"]
pub mod connect;
#[path = "fetch.rs"]
pub mod fetch;
#[path = "play.rs"]
pub mod play;
#[path = "player.rs"]
pub mod player;
#[path = "register.rs"]
pub mod register;
#[path = "status.rs"]
pub mod status;
