#[path = "api/connect.rs"]
pub mod connect;
#[path = "api/fetch.rs"]
pub mod fetch;
#[path = "api/play.rs"]
pub mod play;
#[path = "api/register.rs"]
pub mod register;
#[path = "api/status.rs"]
pub mod status;
